In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tqdm import tqdm

Using TensorFlow backend.


In [2]:
train = pd.read_csv('train_new.csv')

In [3]:
train

id  label
0          1      9
1          2      0
2          3      0
3          4      3
4          5      0
5          6      2
6          7      7
7          8      2
8          9      5
9         10      5
10        11      0
11        12      9
12        13      5
13        14      5
14        15      7
15        16      9
16        17      1
17        18      0
18        19      6
19        20      4
20        21      3
21        22      1
22        23      4
23        24      8
24        25      4
25        26      3
26        27      0
27        28      2
28        29      4
29        30      4
...      ...    ...
59970  59971      9
59971  59972      3
59972  59973      5
59973  59974      6
59974  59975      0
59975  59976      4
59976  59977      4
59977  59978      2
59978  59979      9
59979  59980      7
59980  59981      3
59981  59982      2
59982  59983      4
59983  59984      5
59984  59985      4
59985  59986      0
59986  59987      4
59987  59988      6
59988  59989      6
59989  59990      1
59990  59991      4
59991  59992      1
59992  59993      7
59993  59994      2
59994  59995      8
59995  59996      5
59996  59997      1
59997  59998      3
59998  59999      0
59999  60000      5

[60000 rows x 2 columns]

In [4]:
# We have grayscale images, so while loading the images we will keep grayscale=True, if you have RGB images, you should set grayscale as False
train_image = []
for i in tqdm(range(train.shape[0])):
    img = image.load_img('train_new/'+train['id'][i].astype('str')+'.png', target_size=(28,28,1), grayscale=True)
    img = image.img_to_array(img)
    img = img/255
    train_image.append(img)
X = np.array(train_image)
print(X[0])

  0%|          | 0/60000 [00:00<?, ?it/s]/home/harish/anaconda3/lib/python3.7/site-packages/keras_preprocessing/image/utils.py:104: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '
100%|██████████| 60000/60000 [00:21<00:00, 2766.58it/s]


[[[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0. 

In [5]:
train.dtypes

id       int64
label    int64
dtype: object

In [6]:
y=train['label'].values
y = to_categorical(y)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [8]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(28,28,1)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

W1011 00:46:38.093573 140387201574720 deprecation_wrapper.py:119] From /home/harish/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W1011 00:46:38.119365 140387201574720 deprecation_wrapper.py:119] From /home/harish/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1011 00:46:38.125035 140387201574720 deprecation_wrapper.py:119] From /home/harish/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W1011 00:46:38.199259 140387201574720 deprecation_wrapper.py:119] From /home/harish/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W1011 0

In [9]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

W1011 00:46:38.786273 140387201574720 deprecation_wrapper.py:119] From /home/harish/anaconda3/lib/python3.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W1011 00:46:38.837049 140387201574720 deprecation_wrapper.py:119] From /home/harish/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [10]:
model.fit(X_train, y_train, epochs=1, validation_data=(X_test, y_test))

W1011 00:46:39.825222 140387201574720 deprecation.py:323] From /home/harish/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 48000 samples, validate on 12000 samples
Epoch 1/1
48000/48000 [==============================] - 121s 3ms/step - loss: 0.4918 - acc: 0.8243 - val_loss: 0.3147 - val_acc: 0.8850


In [26]:
test = pd.read_csv('test_new.csv')

In [27]:
test_image = []
for i in tqdm(range(test.shape[0])):
    img = image.load_img('test_new/'+test['id'][i].astype('str')+'.png', target_size=(28,28,1), grayscale=True)
    img = image.img_to_array(img)
    img = img/255
    test_image.append(img)
test = np.array(test_image)
print(test)

100%|██████████| 10000/10000 [00:17<00:00, 562.26it/s]

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [28]:
prediction = model.predict_classes(test)

In [31]:
print(prediction)

[9 2 1 ... 8 1 5]


In [32]:
# creating submission file
sample = pd.read_csv('sample_submission_I5njJSF.csv')
sample['label'] = prediction
sample.to_csv('sample_cnn.csv', header=True, index=False)

In [33]:
df=pd.read_csv('sample_cnn.csv')

In [34]:
df

id  label
0     60001      9
1     60002      2
2     60003      1
3     60004      1
4     60005      6
5     60006      1
6     60007      4
7     60008      6
8     60009      5
9     60010      7
10    60011      4
11    60012      5
12    60013      5
13    60014      3
14    60015      4
15    60016      1
16    60017      2
17    60018      6
18    60019      8
19    60020      0
20    60021      2
21    60022      5
22    60023      7
23    60024      5
24    60025      1
25    60026      6
26    60027      6
27    60028      0
28    60029      9
29    60030      3
...     ...    ...
9970  69971      2
9971  69972      6
9972  69973      6
9973  69974      9
9974  69975      7
9975  69976      8
9976  69977      5
9977  69978      0
9978  69979      9
9979  69980      0
9980  69981      0
9981  69982      0
9982  69983      8
9983  69984      1
9984  69985      3
9985  69986      3
9986  69987      7
9987  69988      5
9988  69989      8
9989  69990      4
9990  69991      5
9991  69992      0
9992  69993      8
9993  69994      9
9994  69995      1
9995  69996      9
9996  69997      1
9997  69998      8
9998  69999      1
9999  70000      5

[10000 rows x 2 columns]